use message::IrcMessage;

use watchers::join::JoinResult;
use watchers::who::WhoResult;


/// An event, which is usually generated by reading a line from the server.
#[deriving(Show)]
pub enum IrcEvent {
	/// An IRC message from the server
    IrcEventMessage(IrcMessage),
    /// The bundled result of a JOIN command
    IrcEventJoinBundle(JoinResult),
    /// The bundled result of a WHO command
    IrcEventWhoBundle(WhoResult)
}
