pub const ERR_NONICKNAMEGIVEN: i32 = 431;
pub const ERR_NICKNAMEINUSE: i32 = 433;
pub const ERR_UNAVAILRESOURCE: i32 = 437;
pub const ERR_ERRONEUSNICKNAME: i32 = 432;
pub const ERR_NICKCOLLISION: i32 = 436;
pub const ERR_RESTRICTED: i32 = 484;



// join error codes:
// ERR_NEEDMOREPARAMS
// ERR_BANNEDFROMCHAN
// ERR_INVITEONLYCHAN
// ERR_BADCHANNELKEY
// ERR_CHANNELISFULL
// ERR_BADCHANMASK
// ERR_NOSUCHCHANNEL
// ERR_TOOMANYCHANNELS
// ERR_TOOMANYTARGETS
// ERR_UNAVAILRESOURCE
// RPL_TOPIC
